# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/earth/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),earth)

$(call add-radio-file-sha1-checked,radio/gz.img,b73ed8a759e1e29a4f3ff4016fc10ba6973569bd)
$(call add-radio-file-sha1-checked,radio/lk.img,9341c557fa1554a321270acd9d0912c1e340ffb7)
$(call add-radio-file-sha1-checked,radio/logo.img,d1e1b02281897e3e539c35956614e2d2b876b33f)
$(call add-radio-file-sha1-checked,radio/md1img.img,7a4e5d9c1ec7f49dd4ff2ae7cf325e98fd050a24)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,9d5562429dea6c7cb7661bf31ba82f1fed228016)
$(call add-radio-file-sha1-checked,radio/scp.img,2167b587a8a49e0df2b3f50c647f75ea84c015e6)
$(call add-radio-file-sha1-checked,radio/spmfw.img,27014ff6345ce1c22c17d4e648fafebc55cf8684)
$(call add-radio-file-sha1-checked,radio/sspm.img,633419a6501ab650d6a1509c3ff774e8b645db5d)
$(call add-radio-file-sha1-checked,radio/tee.img,145eecce0b84573ec8ca8bc1601e4380d1ba398d)

endif
